/* GENERATED by meshtool/cubetable.py --nofill - do not edit.
 * The cube grid's per-vertex chamfer table WITHOUT interior (concave) chamfers: for each vertex body
 * (canonical mask) and r/g regime, the chamfer surface inside the
 * dual cell about the vertex (1,1,1) of the 2x2x2 body, as polygons
 * whose vertex coordinates are a + b*g + c*r.
 * Generated offline by the table generator (meshtool/cubetable.py in the
 * author's chamfer working tree, not part of this repository): the
 * with-fill surface comes from a direct chamfer tracer, the no-fill one
 * from a Minkowski construction, each fitted as affine formulas in g and
 * r per r/g regime and verified at every sweep ratio. */
#ifndef CUBETABLE_NOFILL_H
#define CUBETABLE_NOFILL_H

/* cases are keyed by their canonical mask (the least image under the 48
 * symmetries of the cube about the vertex); the symmetries, the map from
 * a vertex mask to its case and the split of a mask into face-connected
 * pieces are computed at runtime (cubemesh.cpp) */
#ifndef CUBETABLE_TYPES_H
#define CUBETABLE_TYPES_H
/* a polygon with triangles (triStart[i] < triStart[i+1]) is a non-planar hole patch: its
 * triangulation is given (index triples into its vertex list); planar polygons have none */
struct cubeRegime_s { double lo, hi; int nVert; const double * vert; int nPoly; const int * polyStart; const int * polyVert; const int * triStart; const int * triVert; };
struct cubeCase_s { int mask; int nRegime; const cubeRegime_s * regime; };
#endif

static const double cubeNFVert_1_0[] = {
  0.5,0,0,1,-1,-1,1,-1,0,
  0.5,0,0,0.5,0,0,1,-1,0,
  1,-1,-1,0.5,0,0,1,-1,0,
  1,-1,-1,1,-1,-1,1,-1,0,
  1,-1,0,0.5,0,0,1,-1,-1,
  1,-1,0,0.5,0,0,0.5,0,0,
  1,-1,0,1,-1,-1,0.5,0,0,
  1,-1,0,1,-1,-1,1,-1,-1,
  0.5,0,0,1,-1,0,0.5,0,0,
  0.5,0,0,1,-1,0,1,-1,-1,
  1,-1,-1,1,-1,0,1,-1,-1,
  1,-1,-1,1,-1,0,0.5,0,0,
};
static const int cubeNFPolyStart_1_0[] = {0,4,8,12,16,20,24,27};
static const int cubeNFPolyVert_1_0[] = {0,1,2,3,4,5,6,7,8,9,10,11,3,2,4,7,11,10,7,6,9,0,3,10,10,3,7};
static const int cubeNFTriStart_1_0[] = {0,0,0,0,0,0,0,0};
static const int cubeNFTriVert_1_0[] = {0};
static const cubeRegime_s cubeNFRegimes_1[] = {
  {0.000000000, 6.000000000, 12, cubeNFVert_1_0, 7, cubeNFPolyStart_1_0, cubeNFPolyVert_1_0, cubeNFTriStart_1_0, cubeNFTriVert_1_0},
};
static const double cubeNFVert_3_0[] = {
  1,-1,0,0.5,0,0,1.5,0,0,
  1,-1,0,0.5,0,0,0.5,0,0,
  1,-1,0,1,-1,-1,0.5,0,0,
  1,-1,0,1,-1,-1,1.5,0,0,
  0.5,0,0,1,-1,0,0.5,0,0,
  0.5,0,0,1,-1,0,1.5,0,0,
  1,-1,-1,1,-1,0,1.5,0,0,
  1,-1,-1,1,-1,0,0.5,0,0,
};
static const int cubeNFPolyStart_3_0[] = {0,4,8,12};
static const int cubeNFPolyVert_3_0[] = {0,1,2,3,4,5,6,7,7,6,3,2};
static const int cubeNFTriStart_3_0[] = {0,0,0,0};
static const int cubeNFTriVert_3_0[] = {0};
static const cubeRegime_s cubeNFRegimes_3[] = {
  {0.000000000, 6.000000000, 8, cubeNFVert_3_0, 3, cubeNFPolyStart_3_0, cubeNFPolyVert_3_0, cubeNFTriStart_3_0, cubeNFTriVert_3_0},
};
static const double cubeNFVert_7_0[] = {
  1,-1,0,1,-1,0,1,-1,-1,
  1,-1,0,1,-1,-1,1,-1,0,
  1,-1,0,1,-1,-1,1.5,0,0,
  1,-1,0,0.5,0,0,1.5,0,0,
  1,-1,0,0.5,0,0,0.5,0,0,
  1,-1,0,1.5,0,0,0.5,0,0,
  1,-1,0,1.5,0,0,1,-1,-1,
  0.5,0,0,1,-1,0,1,-1,0,
  0.5,0,0,1,-1,0,1.5,0,0,
  1,-1,-1,1,-1,0,1.5,0,0,
  1,-1,-1,1,-1,0,1,-1,0,
  0.5,0,0,1.5,0,0,1,-1,0,
  1,-1,-1,1.5,0,0,1,-1,0,
};
static const int cubeNFPolyStart_7_0[] = {0,7,11,15,19,23,26};
static const int cubeNFPolyVert_7_0[] = {0,1,2,3,4,5,6,7,8,9,10,11,7,10,12,12,10,0,6,10,9,2,1,10,1,0};
static const int cubeNFTriStart_7_0[] = {0,0,0,0,0,0,0};
static const int cubeNFTriVert_7_0[] = {0};
static const cubeRegime_s cubeNFRegimes_7[] = {
  {0.000000000, 6.000000000, 13, cubeNFVert_7_0, 6, cubeNFPolyStart_7_0, cubeNFPolyVert_7_0, cubeNFTriStart_7_0, cubeNFTriVert_7_0},
};
static const double cubeNFVert_15_0[] = {
  1,-1,0,0.5,0,0,1.5,0,0,
  1,-1,0,0.5,0,0,0.5,0,0,
  1,-1,0,1.5,0,0,0.5,0,0,
  1,-1,0,1.5,0,0,1.5,0,0,
};
static const int cubeNFPolyStart_15_0[] = {0,4};
static const int cubeNFPolyVert_15_0[] = {0,1,2,3};
static const int cubeNFTriStart_15_0[] = {0,0};
static const int cubeNFTriVert_15_0[] = {0};
static const cubeRegime_s cubeNFRegimes_15[] = {
  {0.000000000, 6.000000000, 4, cubeNFVert_15_0, 1, cubeNFPolyStart_15_0, cubeNFPolyVert_15_0, cubeNFTriStart_15_0, cubeNFTriVert_15_0},
};
static const double cubeNFVert_23_0[] = {
  1,-1,0,0.5,0,0,1.5,0,0,
  1,-1,0,0.5,0,0,1,-1,0,
  1,-1,0,1,-1,-1,1,-1,0,
  1,-1,0,1,-1,-1,1.5,0,0,
  1,-1,0,1,-1,0,1,-1,-1,
  1,-1,0,1,-1,0,0.5,0,0,
  1,-1,0,1.5,0,0,0.5,0,0,
  1,-1,0,1.5,0,0,1,-1,-1,
  0.5,0,0,1,-1,0,1,-1,0,
  0.5,0,0,1,-1,0,1.5,0,0,
  1,-1,-1,1,-1,0,1.5,0,0,
  1,-1,-1,1,-1,0,1,-1,0,
  1.5,0,0,1,-1,0,1,-1,-1,
  1.5,0,0,1,-1,0,0.5,0,0,
  0.5,0,0,1.5,0,0,1,-1,0,
  1,-1,-1,1.5,0,0,1,-1,0,
  1.5,0,0,0.5,0,0,1,-1,0,
  1.5,0,0,1,-1,-1,1,-1,0,
};
static const int cubeNFPolyStart_23_0[] = {0,4,8,12,16,20,24,28,32,36,39};
static const int cubeNFPolyVert_23_0[] = {0,1,2,3,4,5,6,7,8,9,10,11,5,4,12,13,14,8,11,15,2,1,16,17,15,11,4,7,11,10,3,2,4,2,17,12,11,2,4};
static const int cubeNFTriStart_23_0[] = {0,0,0,0,0,0,0,0,0,0,0};
static const int cubeNFTriVert_23_0[] = {0};
static const cubeRegime_s cubeNFRegimes_23[] = {
  {0.000000000, 6.000000000, 18, cubeNFVert_23_0, 10, cubeNFPolyStart_23_0, cubeNFPolyVert_23_0, cubeNFTriStart_23_0, cubeNFTriVert_23_0},
};
static const double cubeNFVert_27_0[] = {
  0.5,0,0,1,-1,0,0.5,0,0,
  0.5,0,0,1,-1,0,1,1,0,
  1,-1,-1,1,-1,0,1,1,0,
  1,-1,-1,1,-1,0,1,-1,0,
  1,-1,0,1,-1,0,1,-1,-1,
  1.5,0,0,1,-1,0,1,-1,-1,
  1.5,0,0,1,-1,0,0.5,0,0,
  1,-1,0,0.5,0,0,1.5,0,0,
  1,-1,0,0.5,0,0,1,-1,0,
  1,-1,0,1,-1,-1,1,-1,0,
  1,-1,0,1,-1,-1,1,1,0,
  1,-1,0,1,-1,0,1,1,1,
  1,-1,0,1.5,0,0,1,1,1,
  1,-1,0,1.5,0,0,1.5,0,0,
  0.5,0,0,1.5,0,0,1,1,0,
  1,-1,-1,1.5,0,0,1,1,0,
  1.5,0,0,0.5,0,0,1,-1,0,
  1.5,0,0,1,-1,-1,1,-1,0,
};
static const int cubeNFPolyStart_27_0[] = {0,7,14,18,22,26,30,33,36,40};
static const int cubeNFPolyVert_27_0[] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,1,14,15,2,9,8,16,17,4,9,17,5,2,15,12,11,3,9,4,2,11,10,9,3,2,10};
static const int cubeNFTriStart_27_0[] = {0,0,0,0,0,0,0,0,0,0};
static const int cubeNFTriVert_27_0[] = {0};
static const cubeRegime_s cubeNFRegimes_27[] = {
  {0.000000000, 6.000000000, 18, cubeNFVert_27_0, 9, cubeNFPolyStart_27_0, cubeNFPolyVert_27_0, cubeNFTriStart_27_0, cubeNFTriVert_27_0},
};
static const double cubeNFVert_31_0[] = {
  1,-1,0,0.5,0,0,1.5,0,0,
  1,-1,0,0.5,0,0,1,-1,0,
  1,-1,0,1,-1,-1,1,-1,0,
  1,-1,0,1,-1,0,1,-1,-1,
  1,-1,0,1,-1,0,0.5,0,0,
  1,-1,0,1.5,0,0,0.5,0,0,
  1,-1,0,1.5,0,0,1.5,0,0,
  1.5,0,0,0.5,0,0,1,-1,0,
  1.5,0,0,1,-1,-1,1,-1,0,
  1.5,0,0,1,-1,0,1,-1,-1,
  1.5,0,0,1,-1,0,0.5,0,0,
};
static const int cubeNFPolyStart_31_0[] = {0,7,11,15,19};
static const int cubeNFPolyVert_31_0[] = {0,1,2,3,4,5,6,2,1,7,8,4,3,9,10,3,2,8,9};
static const int cubeNFTriStart_31_0[] = {0,0,0,0,0};
static const int cubeNFTriVert_31_0[] = {0};
static const cubeRegime_s cubeNFRegimes_31[] = {
  {0.000000000, 6.000000000, 11, cubeNFVert_31_0, 4, cubeNFPolyStart_31_0, cubeNFPolyVert_31_0, cubeNFTriStart_31_0, cubeNFTriVert_31_0},
};
static const double cubeNFVert_61_0[] = {
  1,-1,0,1,1,1,1.5,0,0,
  1,-1,0,1,1,1,1,-1,0,
  1,-1,0,1,-1,0,1,-1,0,
  1,-1,0,1,-1,0,0.5,0,0,
  1,-1,0,1.5,0,0,0.5,0,0,
  1,-1,0,1.5,0,0,1.5,0,0,
  1,1,1,1,-1,0,1,-1,0,
  1,1,1,1,-1,0,1.5,0,0,
  1.5,0,0,1,-1,0,1.5,0,0,
  1.5,0,0,1,-1,0,0.5,0,0,
  1,-1,-1,1,1,0,1,-1,0,
  0.5,0,0,1,1,0,1,-1,0,
  0.5,0,0,0.5,0,0,1,-1,0,
  1,1,0,0.5,0,0,1,-1,0,
  1,1,0,1,-1,-1,1,-1,0,
  1,1,0,0.5,0,0,1.5,0,0,
  1,1,0,1,-1,-1,1.5,0,0,
  0.5,0,0,1,1,0,1.5,0,0,
  1,-1,-1,1,1,0,1.5,0,0,
};
static const int cubeNFPolyStart_61_0[] = {0,6,12,20,24,28,32,36};
static const int cubeNFPolyVert_61_0[] = {0,1,2,3,4,5,3,2,6,7,8,9,2,1,10,11,12,13,14,6,13,15,16,14,17,11,10,18,14,16,7,6,18,10,1,0};
static const int cubeNFTriStart_61_0[] = {0,0,0,0,0,0,0,0};
static const int cubeNFTriVert_61_0[] = {0};
static const cubeRegime_s cubeNFRegimes_61[] = {
  {0.000000000, 6.000000000, 19, cubeNFVert_61_0, 7, cubeNFPolyStart_61_0, cubeNFPolyVert_61_0, cubeNFTriStart_61_0, cubeNFTriVert_61_0},
};
static const double cubeNFVert_63_0[] = {
  1,-1,0,1,-1,0,1.5,0,0,
  1,-1,0,1,-1,0,0.5,0,0,
  1,-1,0,1.5,0,0,0.5,0,0,
  1,-1,0,1.5,0,0,1.5,0,0,
  1.5,0,0,1,-1,0,1.5,0,0,
  1.5,0,0,1,-1,0,0.5,0,0,
};
static const int cubeNFPolyStart_63_0[] = {0,4,8};
static const int cubeNFPolyVert_63_0[] = {0,1,2,3,1,0,4,5};
static const int cubeNFTriStart_63_0[] = {0,0,0};
static const int cubeNFTriVert_63_0[] = {0};
static const cubeRegime_s cubeNFRegimes_63[] = {
  {0.000000000, 6.000000000, 6, cubeNFVert_63_0, 2, cubeNFPolyStart_63_0, cubeNFPolyVert_63_0, cubeNFTriStart_63_0, cubeNFTriVert_63_0},
};
static const double cubeNFVert_111_0[] = {
  1,-1,0,1,-1,0,1.5,0,0,
  1,-1,0,1,-1,0,1,1,1,
  1,-1,0,1,-1,-1,1,1,0,
  1,-1,0,0.5,0,0,1,1,0,
  1,-1,0,0.5,0,0,0.5,0,0,
  1,-1,0,1,1,0,0.5,0,0,
  1,-1,0,1,1,0,1,-1,-1,
  1,-1,0,1,1,1,1,-1,0,
  1,-1,0,1.5,0,0,1,-1,0,
  1,-1,0,1.5,0,0,1.5,0,0,
  1.5,0,0,1,1,0,0.5,0,0,
  1.5,0,0,1,1,0,1,-1,-1,
  1.5,0,0,1,-1,-1,1,1,0,
  1.5,0,0,0.5,0,0,1,1,0,
  1.5,0,0,1,-1,0,1.5,0,0,
  1.5,0,0,1,-1,0,1,1,1,
  1.5,0,0,1,1,1,1,-1,0,
  1.5,0,0,1.5,0,0,1,-1,0,
};
static const int cubeNFPolyStart_111_0[] = {0,10,14,18,22,26,30,34};
static const int cubeNFPolyVert_111_0[] = {0,1,2,3,4,5,6,7,8,9,6,5,10,11,3,2,12,13,1,0,14,15,8,7,16,17,2,1,15,12,7,6,11,16};
static const int cubeNFTriStart_111_0[] = {0,0,0,0,0,0,0,0};
static const int cubeNFTriVert_111_0[] = {0};
static const cubeRegime_s cubeNFRegimes_111[] = {
  {0.000000000, 6.000000000, 18, cubeNFVert_111_0, 7, cubeNFPolyStart_111_0, cubeNFPolyVert_111_0, cubeNFTriStart_111_0, cubeNFTriVert_111_0},
};
static const double cubeNFVert_126_0[] = {
  1,1,0,0.5,0,0,0.5,0,0,
  1,1,0,0.5,0,0,1,1,0,
  1,1,0,1,-1,0,1,1,0,
  1,1,0,1,-1,0,1,-1,0,
  1,1,0,1,1,0,1,-1,0,
  1,1,0,1,1,0,0.5,0,0,
  0.5,0,0,0.5,0,0,1,1,0,
  0.5,0,0,1,1,0,1,1,0,
  1,-1,0,1,1,0,1,1,0,
  1,-1,0,1,-1,0,1,1,0,
  1,-1,0,1,1,0,1,-1,0,
  0.5,0,0,1,1,0,0.5,0,0,
  1,-1,0,1,-1,0,1.5,0,0,
  1,-1,0,1.5,0,0,1,-1,0,
  1,-1,0,1.5,0,0,1.5,0,0,
  1.5,0,0,1,-1,0,1.5,0,0,
  1.5,0,0,1,-1,0,1,-1,0,
  1.5,0,0,1.5,0,0,1,-1,0,
};
static const int cubeNFPolyStart_126_0[] = {0,6,12,18,24,30,36};
static const int cubeNFPolyVert_126_0[] = {0,1,2,3,4,5,6,7,8,9,2,1,4,10,8,7,11,5,12,9,8,10,13,14,3,2,9,12,15,16,13,10,4,3,16,17};
static const int cubeNFTriStart_126_0[] = {0,0,0,0,0,0,0};
static const int cubeNFTriVert_126_0[] = {0};
static const cubeRegime_s cubeNFRegimes_126[] = {
  {0.000000000, 6.000000000, 18, cubeNFVert_126_0, 6, cubeNFPolyStart_126_0, cubeNFPolyVert_126_0, cubeNFTriStart_126_0, cubeNFTriVert_126_0},
};
static const double cubeNFVert_127_0[] = {
  1,-1,0,1.5,0,0,1,-1,0,
  1,-1,0,1,-1,0,1,-1,0,
  1.5,0,0,1,-1,0,1,-1,0,
  1.5,0,0,1.5,0,0,1,-1,0,
  1,-1,0,1,-1,0,1.5,0,0,
  1,-1,0,1.5,0,0,1.5,0,0,
  1.5,0,0,1,-1,0,1.5,0,0,
};
static const int cubeNFPolyStart_127_0[] = {0,4,8,12};
static const int cubeNFPolyVert_127_0[] = {0,1,2,3,4,1,0,5,1,4,6,2};
static const int cubeNFTriStart_127_0[] = {0,0,0,0};
static const int cubeNFTriVert_127_0[] = {0};
static const cubeRegime_s cubeNFRegimes_127[] = {
  {0.000000000, 6.000000000, 7, cubeNFVert_127_0, 3, cubeNFPolyStart_127_0, cubeNFPolyVert_127_0, cubeNFTriStart_127_0, cubeNFTriVert_127_0},
};
static const int cubeNFNumCases = 12;
static const cubeCase_s cubeNFCases[] = {
  {1, 1, cubeNFRegimes_1},
  {3, 1, cubeNFRegimes_3},
  {7, 1, cubeNFRegimes_7},
  {15, 1, cubeNFRegimes_15},
  {23, 1, cubeNFRegimes_23},
  {27, 1, cubeNFRegimes_27},
  {31, 1, cubeNFRegimes_31},
  {61, 1, cubeNFRegimes_61},
  {63, 1, cubeNFRegimes_63},
  {111, 1, cubeNFRegimes_111},
  {126, 1, cubeNFRegimes_126},
  {127, 1, cubeNFRegimes_127},
};

#endif
