#!/usr/bin/env python3
"""Regression test suite for burrTxt and burrTxt2 against the official 0.7.1 release.

This script runs example puzzles through burrTxt and burrTxt2, comparing results
against a known-good reference state generated by the official BurrTools 0.7.1
release.

Key Design Points:
1. Invariants tested:
   - Assembly counts (rotation- and permutation-invariant)
   - Disassembly / solution counts
   - Disassembly move sequences / levels (da->movesText())
   - Return codes and error states (e.g. piece placement impossibility)
   - Solutions saved in <file>ttt by burrTxt2
   - Exact iteration counts are NOT asserted (per repo guidelines in AGENTS.md,
     iterations measure internal search-tree node visits and change with search
     heuristics and SIMD optimizations).
2. burrTxt2 non-interactive execution:
   burrTxt2 select()s on STDIN_FILENO and treats readable stdin (including EOF)
   as an abort request. This script hands it the read end of an os.pipe() and
   keeps the write end open in the parent process for the duration of the run.
3. Hermetic execution:
   burrTxt2 modifies and writes <file>ttt next to the puzzle file. All runs are
   performed in isolated temporary directories on scratch copies.
4. Grids without disassembler:
   Rhombic, honeycomb, and tetra-octa grids do not have a movement cache in
   BurrTools. Disassembly tests are only run on grids that support disassembly
   (Cubic / Bricks and Triangular Prism).
"""

import argparse
import glob
import gzip
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path

DEFAULT_TIMEOUT = 60
SLOW_PUZZLES = {"Burr-Glar.xmpuzzle"}

RELEASE_0_7_1_URLS = {
    "burrTxt": "https://github.com/burr-tools/burr-tools/releases/download/v0.7.1/burrTxt",
    "burrTxt2": "https://github.com/burr-tools/burr-tools/releases/download/v0.7.1/burrTxt2",
    "tarball": "https://github.com/burr-tools/burr-tools/releases/download/v0.7.1/burrtools-v0.7.1-linux-x86_64.tar.gz",
}


def get_grid_type(puzzle_path: str) -> int:
    """Extract gridType integer from .xmpuzzle file."""
    try:
        with gzip.open(puzzle_path, "rt", encoding="latin-1", errors="ignore") as f:
            content = f.read(2048)
    except Exception:
        with open(puzzle_path, "rt", encoding="latin-1", errors="ignore") as f:
            content = f.read(2048)
    m = re.search(r'<gridType\s+type="(\d+)"', content)
    return int(m.group(1)) if m else -1


def supports_disassembly(grid_type: int) -> bool:
    """Return True if grid type supports disassembly (Cubic=0, Triangular Prism=1)."""
    return grid_type in (0, 1)


def parse_burrtxt_output(stdout: str, returncode: int) -> dict:
    """Parse burrTxt output into structured metrics."""
    result = {
        "returncode": returncode,
        "assemblies": 0,
        "solutions": 0,
        "moves": [],
        "errors": [],
        "problems": [],
    }

    current_problem = None
    for line in stdout.splitlines():
        line = line.strip()
        m_prob = re.match(r"^problem\s+(\d+)(?:\s*\((.*?)\))?", line, re.IGNORECASE)
        if m_prob:
            current_problem = {
                "id": int(m_prob.group(1)),
                "name": m_prob.group(2) or "",
                "assemblies": 0,
                "solutions": 0,
                "moves": [],
            }
            result["problems"].append(current_problem)

        m_moves = re.match(r"^level:\s*([0-9.]+)", line)
        if m_moves:
            level = m_moves.group(1)
            result["moves"].append(level)
            if current_problem is not None:
                current_problem["moves"].append(level)

        m_res = re.search(r"(\d+)\s+assemblies\s+and\s+(\d+)\s+solutions\s+found", line)
        if m_res:
            asms = int(m_res.group(1))
            sols = int(m_res.group(2))
            result["assemblies"] += asms
            result["solutions"] += sols
            if current_problem is not None:
                current_problem["assemblies"] = asms
                current_problem["solutions"] = sols

        if "Piece " in line and "can be place" in line:
            result["errors"].append(line)
        elif "units too" in line:
            result["errors"].append(line)
        elif "features not yet supported" in line:
            result["errors"].append(line)

    return result


def run_burrtxt(binary: str, puzzle_path: str, disassemble: bool = False, timeout: int = DEFAULT_TIMEOUT) -> dict:
    """Run burrTxt on a puzzle file."""
    args = [binary, "-q", "-o", "all"]
    if disassemble:
        args.append("-d")
    args.append(puzzle_path)

    t0 = time.time()
    try:
        proc = subprocess.run(args, capture_output=True, text=True, timeout=timeout)
        elapsed = time.time() - t0
        parsed = parse_burrtxt_output(proc.stdout, proc.returncode)
        parsed["elapsed_sec"] = round(elapsed, 3)
        return parsed
    except subprocess.TimeoutExpired:
        return {
            "returncode": -1,
            "assemblies": 0,
            "solutions": 0,
            "moves": [],
            "errors": [f"Timed out after {timeout}s"],
            "problems": [],
            "elapsed_sec": round(time.time() - t0, 3),
        }


def run_burrtxt2(binary: str, burrtxt_binary: str, puzzle_path: str, disassemble: bool = False, timeout: int = DEFAULT_TIMEOUT) -> dict:
    """Run burrTxt2 on a scratch copy of a puzzle file, avoiding stdin abort."""
    with tempfile.TemporaryDirectory() as tmp:
        puzzle_name = Path(puzzle_path).name
        scratch = Path(tmp) / puzzle_name
        shutil.copy(puzzle_path, scratch)

        args = [binary, "-R"]
        if disassemble:
            args.append("-d")
        args.append(str(scratch))

        stdin_r, stdin_w = os.pipe()
        t0 = time.time()
        try:
            proc = subprocess.Popen(
                args,
                stdin=stdin_r,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
            )
            os.close(stdin_r)
            stdin_r = None
            out, _ = proc.communicate(timeout=timeout)
            rc = proc.returncode
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.communicate()
            return {
                "returncode": -1,
                "assemblies": 0,
                "solutions": 0,
                "saved_solutions": 0,
                "status": "TIMEOUT",
                "elapsed_sec": round(time.time() - t0, 3),
            }
        finally:
            if stdin_r is not None:
                os.close(stdin_r)
            os.close(stdin_w)

        elapsed = time.time() - t0
        ttt_file = scratch.with_name(puzzle_name + "ttt")

        saved_sols = 0
        asms = 0
        sols = 0
        if ttt_file.exists():
            try:
                with open(ttt_file, "rt", encoding="latin-1", errors="ignore") as f:
                    content = f.read()
                asms = sum(int(m) for m in re.findall(r'<problem[^>]*\bassemblies="(\d+)"', content))
                sols = sum(int(m) for m in re.findall(r'<problem[^>]*\bsolutions="(\d+)"', content))
                saved_sols = len(re.findall(r"<solution[ >]", content))
            except Exception:
                saved_sols = 0
                asms = 0
                sols = 0

        return {
            "returncode": rc,
            "assemblies": asms,
            "solutions": sols,
            "saved_solutions": saved_sols,
            "status": "done" if "done" in out else ("error" if rc != 0 else "unknown"),
            "elapsed_sec": round(elapsed, 3),
        }


def download_official_0_7_1(dest_dir: str):
    """Download official 0.7.1 release binaries to dest_dir."""
    dest_path = Path(dest_dir)
    dest_path.mkdir(parents=True, exist_ok=True)

    for name in ["burrTxt", "burrTxt2"]:
        target = dest_path / name
        if target.exists() and os.access(target, os.X_OK):
            print(f"Using existing 0.7.1 binary at {target}")
            continue

        url = RELEASE_0_7_1_URLS[name]
        print(f"Downloading official 0.7.1 {name} from {url}...")
        urllib.request.urlretrieve(url, target)
        target.chmod(0o755)
        print(f"Downloaded and set executable: {target}")


def generate_known_good(release_dir: str, source_root: str, output_path: str, include_slow: bool = False, timeout: int = DEFAULT_TIMEOUT):
    """Generate known-good JSON from official 0.7.1 release."""
    burrtxt = os.path.join(release_dir, "burrTxt")
    burrtxt2 = os.path.join(release_dir, "burrTxt2")

    if not os.path.exists(burrtxt) or not os.path.exists(burrtxt2):
        print(f"Binaries not found in {release_dir}, downloading official 0.7.1 release...")
        download_official_0_7_1(release_dir)

    puzzles = sorted(glob.glob(os.path.join(source_root, "examples", "*.xmpuzzle")))
    data = {
        "version": "0.7.1",
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "puzzles": {},
    }

    print(f"\nGenerating known-good state across {len(puzzles)} puzzles using 0.7.1 release...")
    for p in puzzles:
        rel_path = os.path.relpath(p, source_root)
        name = os.path.basename(p)

        if name in SLOW_PUZZLES and not include_slow:
            print(f"  Skipping slow puzzle: {name}")
            continue

        gt = get_grid_type(p)
        can_disasm = supports_disassembly(gt)
        print(f"  Processing {name:30s} (gridType={gt}, disasm={can_disasm})...")

        # burrTxt assembly
        bt_asm = run_burrtxt(burrtxt, p, disassemble=False, timeout=timeout)

        # burrTxt disassembly
        bt_dis = None
        if can_disasm:
            bt_dis = run_burrtxt(burrtxt, p, disassemble=True, timeout=timeout)

        # burrTxt2 assembly
        bt2_asm = run_burrtxt2(burrtxt2, burrtxt, p, disassemble=False, timeout=timeout)

        # burrTxt2 disassembly
        bt2_dis = None
        if can_disasm:
            bt2_dis = run_burrtxt2(burrtxt2, burrtxt, p, disassemble=True, timeout=timeout)

        puzzle_entry = {
            "grid_type": gt,
            "supports_disassembly": can_disasm,
            "burrTxt_assembly": {
                "returncode": bt_asm["returncode"],
                "assemblies": bt_asm["assemblies"],
                "solutions": bt_asm["solutions"],
                "errors": bt_asm["errors"],
            },
            "burrTxt2_assembly": {
                "returncode": bt2_asm["returncode"],
                "status": bt2_asm["status"],
                "assemblies": bt2_asm["assemblies"],
                "solutions": bt2_asm["solutions"],
                "saved_solutions": bt2_asm["saved_solutions"],
            },
        }

        if bt_dis is not None:
            puzzle_entry["burrTxt_disassembly"] = {
                "returncode": bt_dis["returncode"],
                "assemblies": bt_dis["assemblies"],
                "solutions": bt_dis["solutions"],
                "moves": bt_dis["moves"],
                "errors": bt_dis["errors"],
            }

        if bt2_dis is not None:
            puzzle_entry["burrTxt2_disassembly"] = {
                "returncode": bt2_dis["returncode"],
                "status": bt2_dis["status"],
                "assemblies": bt2_dis["assemblies"],
                "solutions": bt2_dis["solutions"],
                "saved_solutions": bt2_dis["saved_solutions"],
            }

        data["puzzles"][rel_path] = puzzle_entry

    out_file = Path(output_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    with open(out_file, "w") as f:
        json.dump(data, f, indent=2, sort_keys=True)

    print(f"\nKnown-good reference written to {output_path} ({len(data['puzzles'])} puzzles).")


def compare_against_known_good(
    burrtxt: str,
    burrtxt2: str,
    known_good_path: str,
    source_root: str,
    filter_pattern: str = None,
    include_slow: bool = False,
    timeout: int = DEFAULT_TIMEOUT,
) -> int:
    """Run tests against current binaries and compare with known good."""
    if not os.path.exists(known_good_path):
        print(f"Error: Known-good reference file '{known_good_path}' not found.", file=sys.stderr)
        print("Run with --generate-known-good first to create it.", file=sys.stderr)
        return 2

    with open(known_good_path, "r") as f:
        reference = json.load(f)

    puzzles_ref = reference.get("puzzles", {})
    if not puzzles_ref:
        print("Error: Known-good reference file contains no puzzles.", file=sys.stderr)
        return 2

    failures = []
    passed = 0
    total = 0

    print("=" * 80)
    print("BurrTools Regression Test Suite: Comparing against 0.7.1 Release")
    print(f"  burrTxt:   {burrtxt}")
    print(f"  burrTxt2:  {burrtxt2}")
    print(f"  Reference: {known_good_path} (Version: {reference.get('version')})")
    print("=" * 80)

    for rel_path, expected in sorted(puzzles_ref.items()):
        name = os.path.basename(rel_path)
        if filter_pattern and filter_pattern not in name:
            continue
        if name in SLOW_PUZZLES and not include_slow:
            continue

        full_puzzle_path = os.path.join(source_root, rel_path)
        if not os.path.exists(full_puzzle_path):
            print(f"Warning: Puzzle file '{full_puzzle_path}' does not exist, skipping.")
            continue

        total += 1
        can_disasm = expected.get("supports_disassembly", False)
        puzzle_failures = []

        print(f"Testing {name:32s} ...", end=" ", flush=True)

        # 1. Test burrTxt assembly
        exp_asm = expected.get("burrTxt_assembly", {})
        act_asm = run_burrtxt(burrtxt, full_puzzle_path, disassemble=False, timeout=timeout)

        if act_asm["returncode"] != exp_asm["returncode"]:
            puzzle_failures.append(
                f"burrTxt assembly returncode mismatch: expected {exp_asm['returncode']}, got {act_asm['returncode']}"
            )
        if act_asm["assemblies"] != exp_asm["assemblies"]:
            puzzle_failures.append(
                f"burrTxt assemblies count mismatch: expected {exp_asm['assemblies']}, got {act_asm['assemblies']}"
            )
        if exp_asm.get("errors") and not act_asm.get("errors"):
            puzzle_failures.append(
                f"burrTxt expected error missing: expected '{exp_asm['errors']}', got none"
            )

        # 2. Test burrTxt disassembly (if applicable)
        if can_disasm and "burrTxt_disassembly" in expected:
            exp_dis = expected["burrTxt_disassembly"]
            act_dis = run_burrtxt(burrtxt, full_puzzle_path, disassemble=True, timeout=timeout)

            if act_dis["returncode"] != exp_dis["returncode"]:
                puzzle_failures.append(
                    f"burrTxt disassembly returncode mismatch: expected {exp_dis['returncode']}, got {act_dis['returncode']}"
                )
            if act_dis["solutions"] != exp_dis["solutions"]:
                puzzle_failures.append(
                    f"burrTxt disassembly solutions count mismatch: expected {exp_dis['solutions']}, got {act_dis['solutions']}"
                )
            if exp_dis.get("moves") and sorted(act_dis.get("moves", [])) != sorted(exp_dis.get("moves", [])):
                puzzle_failures.append(
                    f"burrTxt disassembly moves mismatch: expected {sorted(exp_dis.get('moves', []))}, got {sorted(act_dis.get('moves', []))}"
                )

        # 3. Test burrTxt2 assembly
        exp_bt2_asm = expected.get("burrTxt2_assembly", {})
        act_bt2_asm = run_burrtxt2(burrtxt2, burrtxt, full_puzzle_path, disassemble=False, timeout=timeout)

        if act_bt2_asm.get("returncode") != exp_bt2_asm.get("returncode"):
            puzzle_failures.append(
                f"burrTxt2 assembly returncode mismatch: expected {exp_bt2_asm.get('returncode')}, got {act_bt2_asm.get('returncode')}"
            )
        if "assemblies" in exp_bt2_asm and act_bt2_asm.get("assemblies", 0) != exp_bt2_asm["assemblies"]:
            puzzle_failures.append(
                f"burrTxt2 assemblies count mismatch: expected {exp_bt2_asm['assemblies']}, got {act_bt2_asm.get('assemblies', 0)}"
            )
        if act_bt2_asm.get("saved_solutions", 0) != exp_bt2_asm.get("saved_solutions", 0):
            puzzle_failures.append(
                f"burrTxt2 saved solutions mismatch: expected {exp_bt2_asm.get('saved_solutions', 0)}, got {act_bt2_asm.get('saved_solutions', 0)}"
            )

        # 4. Test burrTxt2 disassembly (if applicable)
        if can_disasm and "burrTxt2_disassembly" in expected:
            exp_bt2_dis = expected["burrTxt2_disassembly"]
            act_bt2_dis = run_burrtxt2(burrtxt2, burrtxt, full_puzzle_path, disassemble=True, timeout=timeout)

            if act_bt2_dis.get("returncode") != exp_bt2_dis.get("returncode"):
                puzzle_failures.append(
                    f"burrTxt2 disassembly returncode mismatch: expected {exp_bt2_dis.get('returncode')}, got {act_bt2_dis.get('returncode')}"
                )
            if "assemblies" in exp_bt2_dis and act_bt2_dis.get("assemblies", 0) != exp_bt2_dis["assemblies"]:
                puzzle_failures.append(
                    f"burrTxt2 disassembly assemblies count mismatch: expected {exp_bt2_dis['assemblies']}, got {act_bt2_dis.get('assemblies', 0)}"
                )
            if "solutions" in exp_bt2_dis and act_bt2_dis.get("solutions", 0) != exp_bt2_dis["solutions"]:
                puzzle_failures.append(
                    f"burrTxt2 disassembly solutions count mismatch: expected {exp_bt2_dis['solutions']}, got {act_bt2_dis.get('solutions', 0)}"
                )
            if act_bt2_dis.get("saved_solutions", 0) != exp_bt2_dis.get("saved_solutions", 0):
                puzzle_failures.append(
                    f"burrTxt2 disassembly saved solutions mismatch: expected {exp_bt2_dis.get('saved_solutions', 0)}, got {act_bt2_dis.get('saved_solutions', 0)}"
                )

        if puzzle_failures:
            print("FAILED")
            for pf in puzzle_failures:
                print(f"    - {pf}")
                failures.append(f"{name}: {pf}")
        else:
            print("OK")
            passed += 1

    print("=" * 80)
    print(f"Summary: {passed}/{total} puzzles passed regression check.")
    if failures:
        print(f"\n{len(failures)} REGRESSIONS DETECTED:")
        for f in failures:
            print(f"  * {f}")
        return 1

    print("\nAll puzzles match known-good 0.7.1 release state!")
    return 0


def main():
    source_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

    parser = argparse.ArgumentParser(
        description="Regression test suite comparing BurrTools binaries to 0.7.1 release"
    )
    parser.add_argument(
        "--burrtxt",
        default=os.path.join(source_root, "build", "burrTxt"),
        help="Path to burrTxt binary (default: build/burrTxt)",
    )
    parser.add_argument(
        "--burrtxt2",
        default=os.path.join(source_root, "build", "burrTxt2"),
        help="Path to burrTxt2 binary (default: build/burrTxt2)",
    )
    parser.add_argument(
        "--known-good",
        default=os.path.join(source_root, "test", "known_good", "examples_0.7.1.json"),
        help="Path to known-good JSON file (default: test/known_good/examples_0.7.1.json)",
    )
    parser.add_argument(
        "--generate-known-good",
        action="store_true",
        help="Run 0.7.1 release binaries and regenerate the known-good JSON file",
    )
    parser.add_argument(
        "--download-release",
        action="store_true",
        help="Download the official 0.7.1 release binaries",
    )
    parser.add_argument(
        "--release-dir",
        default="/tmp/burr-release-0.7.1",
        help="Directory containing or to receive 0.7.1 release binaries (default: /tmp/burr-release-0.7.1)",
    )
    parser.add_argument(
        "--puzzle",
        help="Filter to puzzle names containing this substring",
    )
    parser.add_argument(
        "--include-slow",
        action="store_true",
        help="Include slow-running puzzles like Burr-Glar (>30s)",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=DEFAULT_TIMEOUT,
        help=f"Per-puzzle solve timeout in seconds (default: {DEFAULT_TIMEOUT})",
    )

    args = parser.parse_args()

    if args.download_release:
        download_official_0_7_1(args.release_dir)
        return 0

    if args.generate_known_good:
        generate_known_good(
            release_dir=args.release_dir,
            source_root=source_root,
            output_path=args.known_good,
            include_slow=args.include_slow,
            timeout=args.timeout,
        )
        return 0

    return compare_against_known_good(
        burrtxt=args.burrtxt,
        burrtxt2=args.burrtxt2,
        known_good_path=args.known_good,
        source_root=source_root,
        filter_pattern=args.puzzle,
        include_slow=args.include_slow,
        timeout=args.timeout,
    )


if __name__ == "__main__":
    sys.exit(main())
