FROM amazonlinux:2017.09
WORKDIR /home/ec2-user
RUN yum -y update
RUN yum -y install fltk boost libpng libXi libXmu mesa-libGL mesa-libGLU freeglut VirtualGL opengl-games-utils glx-utils libXv libXft libXinerama
COPY ./burr-tools /burr
COPY ./burr-tools/libs/* /usr/lib64/
RUN chmod ugo+x /burr/*
USER root
WORKDIR /burr
ENTRYPOINT ["./burrTxt2","-R -d examples/CubeInCage.xmpuzzle"]
