FROM ubuntu:18.04
RUN apt-get -y update
RUN apt-get -y install apt-utils
RUN apt-get -y install freeglut3 libevent-pthreads-2.1-6 libfltk-gl1.3 libglu1-mesa zlib1g libboost-thread1.65.1 libboost-system1.65.1 
COPY ./burr-tools /burr
# COPY ./burr-tools/libs/* /usr/lib64/
RUN chmod ugo+x /burr/*
WORKDIR /burr
USER root
ENTRYPOINT ["./burrTxt2","-R -d examples/CubeInCage.xmpuzzle"]


