#! /bin/sh
set -ex

#
# Total Hack...
#

rm -fv *.o
rm -fv *.a
rm -fv exampleInWebAssembly*

#
# Build the files needed for the core library
#
emcc -DNO_THREADING -I. -Wall -W -Wextra -I/usr/local/include -g -O2 -c \
        ../src/lib/assembler.cpp   \
        ../src/lib/assembler_0.cpp \
        ../src/lib/assembler_1.cpp \
        ../src/lib/assembly.cpp    \
        ../src/lib/bt_assert.cpp   \
        ../src/lib/disasmtomoves.cpp   \
        ../src/lib/disassembler_0.cpp  \
        ../src/lib/disassembler_a.cpp  \
        ../src/lib/disassemblerhashes.cpp  \
        ../src/lib/disassemblernode.cpp    \
        ../src/lib/disassembly.cpp \
        ../src/lib/gridtype.cpp    \
        ../src/lib/grouping.cpp    \
        ../src/lib/millable.cpp    \
        ../src/lib/movementanalysator.cpp  \
        ../src/lib/movementcache.cpp   \
        ../src/lib/movementcache_0.cpp \
        ../src/lib/movementcache_1.cpp \
        ../src/lib/problem.cpp \
        ../src/lib/puzzle.cpp  \
        ../src/lib/solution.cpp    \
        ../src/lib/solvethread.cpp \
        ../src/lib/symmetries_0.cpp    \
        ../src/lib/symmetries_1.cpp    \
        ../src/lib/symmetries_2.cpp    \
        ../src/lib/thread.cpp \
        ../src/lib/voxel.cpp   \
        ../src/lib/voxel_0.cpp \
        ../src/lib/voxel_1.cpp \
        ../src/lib/voxel_2.cpp \
        ../src/lib/voxel_2_mesh.cpp    \
        ../src/lib/voxel_3.cpp \
        ../src/lib/voxel_4.cpp \
        ../src/lib/voxeltable.cpp  \
        ../src/tools/xml.cpp   \
        ../src/lib_interface.cpp 

#
# I would prefer to remove these from the core library, but they're currenty tied in..
#
emcc -DNO_THREADING -I. -Wall -W -Wextra -I/usr/local/include -g -O2 -c \
        ../src/lib/stl.cpp \
        ../src/lib/stl_0.cpp   \
        ../src/lib/stl_2.cpp   \
        ../src/halfedge/face.cpp   \
        ../src/halfedge/halfedge.cpp   \
        ../src/halfedge/modifiers.cpp  \
        ../src/halfedge/polyhedron.cpp \
        ../src/halfedge/vector3.cpp    \
        ../src/halfedge/vertex.cpp \
        ../src/halfedge/volume.cpp


#
# Example of linking into WebAssembly:
#
emcc -I. -Wall -W -Wextra -I/usr/local/include -g -O2 -c ../src/lib_example_c.c
emcc -O2 *.o -o exampleInWebAssembly.html -lstdc++ 

#
# Run the program in Node
#
node exampleInWebAssembly.js

#
# Cleanup
#
rm -fv *.o
