#!/usr/bin/env python3
"""Embed compiled Qt shaders (.qsb) into a C++ source file.

Usage: embed_shaders.py OUTPUT.cpp SHADER.qsb...

Meson cannot hand a .qrc that lists build-time files to rcc, so the shaders
the 3D view compiles with qsb are compiled into the program as byte arrays
instead; burrtoolsShader("mesh.vert.qsb") returns one as a QShader.
"""
import os
import sys


def main():
    out = sys.argv[1]
    files = sys.argv[2:]
    with open(out, 'w') as f:
        f.write('// generated by embed_shaders.py -- do not edit\n')
        # the Qt header first: std headers included before it probe Qt classes
        # that are still only forward-declared, which GCC 16 reports as
        # -Wsfinae-incomplete (an error in the --werror release build)
        f.write('#include <rhi/qshader.h>\n#include <QByteArray>\n#include <cstring>\n\n')
        f.write('namespace {\n')
        for i, path in enumerate(files):
            data = open(path, 'rb').read()
            f.write('const unsigned char shader%d[] = {\n' % i)
            for k in range(0, len(data), 24):
                f.write('  ' + ','.join(str(b) for b in data[k:k + 24]) + ',\n')
            f.write('};\n')
        f.write('}\n\n')
        f.write('QShader burrtoolsShader(const char * name) {\n')
        for i, path in enumerate(files):
            n = os.path.basename(path)
            f.write('  if (!std::strcmp(name, "%s"))\n' % n)
            f.write('    return QShader::fromSerialized(QByteArray::fromRawData('
                    'reinterpret_cast<const char *>(shader%d), sizeof(shader%d)));\n' % (i, i))
        f.write('  return QShader();\n}\n')


if __name__ == '__main__':
    main()
