#!/bin/bash
# Build the macOS .icns files from a rendered puzzle image.
#
# The only historical icon art is burricons.ico at 64x64, far short of the
# 1024x1024 macOS wants, so the icon is a render of an actual puzzle --
# which is also the most honest thing for it to depict.
#
# Producing that render is a manual, one-time step: there is no headless
# rendering path in burrTxt/burrTxt2 or the Python wrapper, so the art is
# made by opening BurrTools itself, loading a visually distinctive puzzle
# (e.g. a six-piece burr from examples/), and using Export > Image at
# 1024x1024 with a transparent background, saved to mac/icon-source.png.
set -e

SRC="${1:-mac/icon-source.png}"
OUT_DIR="mac"

if [ ! -f "$SRC" ]; then
	echo "error: $SRC not found." >&2
	echo "" >&2
	echo "The icon artwork is produced by rendering an actual puzzle through" >&2
	echo "BurrTools' own GUI, not generated by this script. To create it:" >&2
	echo "  1. Build and launch BurrTools (just build && open build/burrtools," >&2
	echo "     or run the compiled binary directly)." >&2
	echo "  2. Load a visually distinctive puzzle from examples/ (a simple" >&2
	echo "     six-piece burr reads better at small sizes than a dense shape)." >&2
	echo "  3. Use Export > Image to render it at 1024x1024 with a" >&2
	echo "     transparent background." >&2
	echo "  4. Save the PNG to ${SRC} and re-run this script." >&2
	exit 1
fi

make_icns() {
	local name="$1"
	local iconset="$(mktemp -d)/${name}.iconset"
	mkdir -p "$iconset"

	for size in 16 32 128 256 512; do
		sips -z $size $size "$SRC" --out "${iconset}/icon_${size}x${size}.png" >/dev/null
		sips -z $((size*2)) $((size*2)) "$SRC" --out "${iconset}/icon_${size}x${size}@2x.png" >/dev/null
	done

	iconutil -c icns "$iconset" -o "${OUT_DIR}/${name}.icns"
	echo "wrote ${OUT_DIR}/${name}.icns"
}

mkdir -p "$OUT_DIR"
make_icns BurrTools
make_icns BurrToolsDoc
