#!/bin/bash
# Build the macOS .icns files from a rendered puzzle image.
#
# The only historical icon art is burricons.ico at 64x64, far short of the
# 1024x1024 macOS wants, so the icon is a render of an actual puzzle --
# which is also the most honest thing for it to depict.
#
# Producing that render is a manual, one-time step: there is no headless
# rendering path in burrTxt/burrTxt2 or the Python wrapper, so the art is
# made by opening BurrTools itself, loading a visually distinctive puzzle
# (e.g. a six-piece burr from examples/), and using Export > Image at
# 1024x1024 with a transparent background, saved to mac/icon-source.png.
set -e

# $1 -- the application artwork.
# $2 -- the document artwork, used for the icon Finder puts on .xmpuzzle
#       files. Optional: if it is missing the app artwork is used instead,
#       with a warning, because two identical icons is a real defect rather
#       than a cosmetic one (see below).
SRC="${1:-mac/icon-source.png}"
DOC_SRC="${2:-mac/icon-source-doc.png}"
OUT_DIR="mac"

if [ ! -f "$SRC" ]; then
	echo "error: $SRC not found." >&2
	echo "" >&2
	echo "The icon artwork is produced by rendering an actual puzzle through" >&2
	echo "BurrTools' own GUI, not generated by this script. To create it:" >&2
	echo "  1. Build and launch BurrTools (just build && open build/burrtools," >&2
	echo "     or run the compiled binary directly)." >&2
	echo "  2. Load a visually distinctive puzzle from examples/ (a simple" >&2
	echo "     six-piece burr reads better at small sizes than a dense shape)." >&2
	echo "  3. Use Export > Image to render it at 1024x1024 with a" >&2
	echo "     transparent background." >&2
	echo "  4. Save the PNG to ${SRC} and re-run this script." >&2
	exit 1
fi

# Scratch space for the .iconset directories, which are an implementation
# detail of iconutil and of no use once the .icns files exist.
#
# One trap at the top level rather than per-call cleanup inside make_icns:
# `set -e` is in force, so a sips or iconutil failure aborts the script
# outright, and an EXIT trap is the only cleanup that still runs on that
# path. (A RETURN trap inside the function would not.)
TMPROOT="$(mktemp -d)"
trap 'rm -rf "$TMPROOT"' EXIT

# Reduce a source image to a centred square, because `sips -z N N` does not
# preserve aspect ratio -- handed a 1066x1093 render it silently squashes the
# artwork rather than complaining.
#
# The square is CROPPED to the smaller dimension rather than padded out to the
# larger one. `sips -c` pads with --padColor, and that flattens the alpha
# channel outright: padding a transparent render produces a solid background,
# which is not what anybody wants on an icon. A pure crop (no padding needed)
# leaves the transparency intact.
#
# The crop is reported rather than done silently, so that artwork whose
# margins are too small to absorb it is visible as clipping in the output
# instead of being discovered later in Finder.
#
# square_source <source png> <destination png>
square_source() {
	local src="$1"
	local dst="$2"

	local w h side
	w=$(sips -g pixelWidth  "$src" | awk '/pixelWidth/  {print $2}')
	h=$(sips -g pixelHeight "$src" | awk '/pixelHeight/ {print $2}')

	if [ "$w" = "$h" ]; then
		cp "$src" "$dst"
		return
	fi

	if [ "$w" -lt "$h" ]; then side="$w"; else side="$h"; fi

	echo "note: ${src} is ${w}x${h}; cropping to a centred ${side}x${side} square" >&2
	echo "      (removing $(( (w - side) / 2 )) px from each side and $(( (h - side) / 2 )) px from top and bottom)." >&2
	echo "      Supply a square source if you want to control the framing yourself." >&2

	sips -c "$side" "$side" "$src" --out "$dst" >/dev/null
}

# make_icns <output name> <source png>
make_icns() {
	local name="$1"
	local src="$2"
	local iconset="${TMPROOT}/${name}.iconset"
	mkdir -p "$iconset"

	local square="${TMPROOT}/${name}-square.png"
	square_source "$src" "$square"
	src="$square"

	for size in 16 32 128 256 512; do
		sips -z $size $size "$src" --out "${iconset}/icon_${size}x${size}.png" >/dev/null
		sips -z $((size*2)) $((size*2)) "$src" --out "${iconset}/icon_${size}x${size}@2x.png" >/dev/null
	done

	iconutil -c icns "$iconset" -o "${OUT_DIR}/${name}.icns"
	echo "wrote ${OUT_DIR}/${name}.icns"
}

mkdir -p "$OUT_DIR"

make_icns BurrTools "$SRC"

# The document icon should NOT be the application icon. Finder shows the
# document icon on every .xmpuzzle file, and the whole point of it is to be
# distinguishable at a glance from the app that opens them -- conventionally
# the app artwork on a page/document shape, so a folder of puzzles does not
# look like a folder of copies of BurrTools.
#
# Until that second piece of artwork exists, fall back to the app artwork and
# say clearly what the fallback costs.
if [ -f "$DOC_SRC" ]; then
	make_icns BurrToolsDoc "$DOC_SRC"
else
	echo "" >&2
	echo "warning: $DOC_SRC not found -- falling back to $SRC for the document icon." >&2
	echo "         BurrTools.icns and BurrToolsDoc.icns will be byte-identical, so" >&2
	echo "         Finder will show the same picture for the application and for" >&2
	echo "         every .xmpuzzle file. That is precisely what a document icon is" >&2
	echo "         supposed to avoid." >&2
	echo "         To fix: render a document-shaped variant of the artwork (the app" >&2
	echo "         image inset on a page/document outline) at 1024x1024 and save it" >&2
	echo "         to ${DOC_SRC}, then re-run this script." >&2
	echo "" >&2
	make_icns BurrToolsDoc "$SRC"
fi
