#!/usr/bin/env python3
"""What a burrtools-qt linked against a static Qt needs beyond the Qt modules.

A static Qt cannot find its plugins at run time: the program has to link
them and name them. This script works both out from the static Qt itself
(meson -Dqt_static=true runs it, src/qtgui/meson.build):

  --link-args   print the link line, one argument per line: the static
                libraries of the Qt modules and of the plugins, Qt's resource
                objects, and every library they need, as Qt's .prl files
                record them
  --cpp FILE    write the C++ that imports the plugins: the platform plugin,
                SVG images, and every QML module the program's QML imports
                (found by qmlimportscanner)

usage: qt_static_link.py --qmake QMAKE --qml-root DIR (--link-args | --cpp FILE)
"""
import argparse
import json
import os
import re
import subprocess
import sys

MODULES = ['Core', 'Gui', 'Network', 'Qml', 'QmlModels', 'QmlMeta', 'QmlWorkerScript', 'Quick',
           'QuickControls2', 'QuickTemplates2', 'Svg']
# Qt Quick Controls styles besides Basic: QtQuick.Controls names them as
# optional imports, but main() sets Basic and the program never leaves it
UNUSED_STYLES = re.compile(r'/Controls/(Universal|Material|Imagine|Fusion|FluentWinUI3|Windows)(/|$)|/NativeStyle(/|$)')
# (plugin directory, plugin, class): the platform, and SVG for the icons and glyphs
PLUGINS = [('platforms', 'qwindows', 'QWindowsIntegrationPlugin'),
           ('imageformats', 'qsvg', 'QSvgPlugin')]


def query(qmake):
    out = subprocess.run([qmake, '-query'], capture_output=True, text=True, check=True).stdout
    return dict(line.split(':', 1) for line in out.splitlines() if ':' in line)


def expand(token, q):
    return re.sub(r'\$\$\[([A-Z_]+)\]', lambda m: q.get(m.group(1), ''), token)


def prl_libs(prl, q):
    """the target and QMAKE_PRL_LIBS of a .prl file, expanded"""
    target, libs = None, []
    with open(prl, encoding='utf-8') as f:
        for line in f:
            key, _, value = line.partition('=')
            key = key.strip()
            if key == 'QMAKE_PRL_TARGET':
                target = os.path.join(os.path.dirname(prl), value.strip())
            elif key == 'QMAKE_PRL_LIBS':
                libs = [expand(t, q) for t in value.split()]
    return target, libs


def qml_plugins(q, qml_root):
    scanner = os.path.join(q['QT_HOST_LIBEXECS'], 'qmlimportscanner')
    if not os.path.exists(scanner) and not os.path.exists(scanner + '.exe'):
        scanner = os.path.join(q['QT_HOST_BINS'], 'qmlimportscanner')
    out = subprocess.run([scanner, '-rootPath', qml_root, '-importPath', q['QT_INSTALL_QML']],
                         capture_output=True, text=True, check=True).stdout
    found = []
    for entry in json.loads(out):
        if entry.get('type') != 'module' or not entry.get('plugin') or not entry.get('classname'):
            continue
        if UNUSED_STYLES.search(entry.get('path', '').replace(os.sep, '/')):
            continue
        prl = os.path.join(entry['path'], entry['plugin'] + '.prl')
        if os.path.exists(prl):
            found.append((prl, entry['classname']))
    return found


def link_args(q, qml_root):
    prls = [os.path.join(q['QT_INSTALL_LIBS'], 'Qt6' + m + '.prl') for m in MODULES]
    prls += [os.path.join(q['QT_INSTALL_PLUGINS'], d, p + '.prl') for d, p, _ in PLUGINS]
    prls += [prl for prl, _ in qml_plugins(q, qml_root)]
    objects, libs, system = [], [], []
    for prl in prls:
        if not os.path.exists(prl):
            continue
        target, deps = prl_libs(prl, q)
        for item in ([target] if target else []) + deps:
            if item.endswith('.obj') or item.endswith('.o'):
                if item not in objects:
                    objects.append(item)
            elif item.startswith('-l') or item.startswith('-L'):
                if item in system:
                    system.remove(item)
                system.append(item)
            else:
                if item in libs:
                    libs.remove(item)
                libs.append(item)
    # the Qt libraries in one group: their order no longer matters
    return objects + ['-Wl,--start-group'] + libs + ['-Wl,--end-group'] + system


def imports_cpp(q, qml_root):
    lines = ['// generated by scripts/qt_static_link.py -- do not edit',
             '// the plugins a static burrtools-qt links and names (meson -Dqt_static=true)',
             '#include <QtPlugin>',
             '#include <QtQml/qqmlextensionplugin.h>', '']
    lines += ['Q_IMPORT_PLUGIN(%s)' % c for _, _, c in PLUGINS]
    seen = set()
    for _, classname in qml_plugins(q, qml_root):
        if classname not in seen:
            seen.add(classname)
            lines.append('Q_IMPORT_QML_PLUGIN(%s)' % classname)
    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--qmake', required=True)
    ap.add_argument('--qml-root', required=True)
    ap.add_argument('--link-args', action='store_true')
    ap.add_argument('--cpp')
    a = ap.parse_args()
    q = query(a.qmake)
    if a.link_args:
        print('\n'.join(link_args(q, a.qml_root)))
    if a.cpp:
        with open(a.cpp, 'w', encoding='utf-8') as f:
            f.write(imports_cpp(q, a.qml_root))
    return 0


if __name__ == '__main__':
    sys.exit(main())
